server:
  port: 8080

spring:
  application:
    name: ucenter-service
  config:
    import: classpath:druid.properties
  messages:
    basename: messages-uc
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      database: 12
      lettuce:
        pool:
          enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: false

apzda:
  cloud:
    config:
      logout-path: /logout
    security:
      meta-repo: redis
      jwt-key: ENC(s2McIm5eJWGWauqTT99Rg7Hm9bLI+F7LeG5vCbTliDDwdW+VYIRtfcYje71NyiGO)
      role-prefix: R_
      credentials-expired-enabled: true
      reset-credentials-path: /~accountService/updatePassword
      mfa-enabled: true
      mfa-exclude: /~accountService/mfaConfig,/~accountService/setupMfa,/~accountService/verifyMfa
  ucenter:
    server:
      props:
        issuer: PosPay

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} %highlight(%-5level) --- [%15.15t] %cyan(%-40.40logger{39}):%-4L - %X{tid} - %msg%n"
